"""
Cross-Camera Correlation Engine

Tracks entities (plates, vehicle descriptions) across multiple cameras.
Detects impossible travel and frequent re-appearances.
"""

import json
import time
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass

import numpy as np

from alibi.encryption import get_encrypted_writer
from alibi.cameras.appearance_reid import cosine_similarity, l2_normalize


@dataclass
class CrossCameraAlert:
    """Alert generated by cross-camera correlation."""
    alert_type: str          # "impossible_travel" | "frequent_reappearance"
    entity_type: str         # "plate" | "vehicle_description"
    entity_id: str           # e.g. "N12345W" or "white_toyota_hilux"
    cameras: List[str]       # Camera IDs involved
    timestamps: List[str]    # ISO timestamps
    message: str
    severity: int            # 1-5


class CrossCameraTracker:
    """
    Tracks entities across cameras and detects patterns.

    In-memory sliding window with periodic JSONL flush for persistence.
    """

    def __init__(
        self,
        min_travel_seconds: float = 300,
        reappearance_window_minutes: float = 30,
        reappearance_camera_threshold: int = 3,
        storage_path: str = "alibi/data/cross_camera_sightings.jsonl",
        retention_hours: int = 24,
    ):
        self.min_travel_seconds = min_travel_seconds
        self.reappearance_window_minutes = reappearance_window_minutes
        self.reappearance_camera_threshold = reappearance_camera_threshold
        self.storage_path = Path(storage_path)
        self.retention_hours = retention_hours
        self._crypto = get_encrypted_writer()

        # In-memory: {entity_key: [(camera_id, timestamp_iso, metadata), ...]}
        self._sightings: Dict[str, List[Dict[str, Any]]] = defaultdict(list)

        # Appearance galleries for ReID matching:
        #   {entity_type: {entity_id: representative_embedding (L2-normalised)}}
        self._galleries: Dict[str, Dict[str, np.ndarray]] = defaultdict(dict)
        # Count of samples averaged into each gallery embedding (running mean).
        self._gallery_counts: Dict[str, Dict[str, int]] = defaultdict(dict)
        # Monotonic counter for minting new appearance-based entity IDs.
        self._new_entity_counter = 0

        self.storage_path.parent.mkdir(parents=True, exist_ok=True)
        self._load_recent()

    def _entity_key(self, entity_type: str, entity_id: str) -> str:
        return f"{entity_type}:{entity_id}"

    def _load_recent(self):
        """Load recent sightings from disk into memory."""
        if not self.storage_path.exists():
            return

        cutoff = datetime.now() - timedelta(hours=self.retention_hours)

        try:
            for record in self._crypto.read_lines(self.storage_path):
                try:
                    ts = datetime.fromisoformat(record["timestamp"])
                    if ts >= cutoff:
                        key = self._entity_key(record["entity_type"], record["entity_id"])
                        self._sightings[key].append({
                            "camera_id": record["camera_id"],
                            "timestamp": record["timestamp"],
                            "metadata": record.get("metadata", {}),
                        })
                except (KeyError, ValueError):
                    continue
        except Exception as e:
            print(f"[CrossCameraTracker] Error loading sightings: {e}")

    def _flush_sighting(self, entity_type: str, entity_id: str, camera_id: str, timestamp: str, metadata: dict):
        """Append a sighting record to JSONL (encrypted at rest)."""
        record = {
            "entity_type": entity_type,
            "entity_id": entity_id,
            "camera_id": camera_id,
            "timestamp": timestamp,
            "metadata": metadata,
        }
        try:
            self._crypto.write_line(self.storage_path, record)
        except Exception as e:
            print(f"[CrossCameraTracker] Error flushing: {e}")

    def record_sighting(
        self,
        camera_id: str,
        entity_type: str,
        entity_id: str,
        timestamp: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> List[CrossCameraAlert]:
        """
        Record an entity sighting and check for cross-camera patterns.

        Returns list of alerts (may be empty).
        """
        if not entity_id or not camera_id:
            return []

        metadata = metadata or {}
        key = self._entity_key(entity_type, entity_id)

        entry = {
            "camera_id": camera_id,
            "timestamp": timestamp,
            "metadata": metadata,
        }

        # Persist
        self._flush_sighting(entity_type, entity_id, camera_id, timestamp, metadata)

        # Add to memory
        self._sightings[key].append(entry)

        # Prune old entries from memory
        cutoff = datetime.now() - timedelta(hours=self.retention_hours)
        self._sightings[key] = [
            s for s in self._sightings[key]
            if self._parse_ts(s["timestamp"]) and self._parse_ts(s["timestamp"]) >= cutoff
        ]

        alerts: List[CrossCameraAlert] = []

        # Check 1: Impossible travel
        alert = self._check_impossible_travel(key, entity_type, entity_id, camera_id, timestamp)
        if alert:
            alerts.append(alert)

        # Check 2: Frequent re-appearance across cameras
        alert = self._check_frequent_reappearance(key, entity_type, entity_id)
        if alert:
            alerts.append(alert)

        return alerts

    def record_appearance_sighting(
        self,
        camera_id: str,
        entity_type: str,
        embedding: Any,
        timestamp: str,
        metadata: Optional[Dict[str, Any]] = None,
        match_threshold: float = 0.6,
        id_prefix: Optional[str] = None,
    ) -> Tuple[str, List[CrossCameraAlert]]:
        """
        Record a sighting identified by APPEARANCE (a ReID embedding) rather
        than an exact string key.

        The embedding is matched by cosine similarity against the recent
        gallery for `entity_type`. If it is close enough to a known entity
        (>= match_threshold), that entity's id is reused — so the SAME vehicle
        or person seen at another camera is correctly linked even with no
        readable plate. Otherwise a new entity id is minted.

        Returns (resolved_entity_id, alerts).
        """
        metadata = metadata or {}
        emb = None
        if embedding is not None:
            emb = np.asarray(embedding, dtype=np.float32).ravel()
            if emb.size == 0:
                emb = None

        entity_id, score = self._resolve_entity_by_appearance(
            entity_type, emb, match_threshold
        )

        if entity_id is None:
            # No match — mint a new appearance-based identity.
            self._new_entity_counter += 1
            prefix = id_prefix or entity_type
            entity_id = f"{prefix}_{self._new_entity_counter:06d}"
            if emb is not None:
                self._galleries[entity_type][entity_id] = l2_normalize(emb)
                self._gallery_counts[entity_type][entity_id] = 1
        else:
            # Matched an existing identity — refine its gallery embedding and
            # annotate the sighting with the match score for auditability.
            if emb is not None:
                self._update_gallery(entity_type, entity_id, emb)
            metadata = {**metadata, "reid_match_score": round(score, 4)}

        alerts = self.record_sighting(
            camera_id, entity_type, entity_id, timestamp, metadata
        )
        return entity_id, alerts

    def _resolve_entity_by_appearance(
        self, entity_type: str, emb: Optional[np.ndarray], match_threshold: float
    ) -> Tuple[Optional[str], float]:
        """
        Find the best-matching known entity of `entity_type` for embedding
        `emb`. Only entities with at least one sighting still inside the
        retention window are considered. Returns (entity_id, score) if the
        best cosine similarity meets the threshold, else (None, best_score).
        """
        if emb is None:
            return None, 0.0

        gallery = self._galleries.get(entity_type, {})
        best_id: Optional[str] = None
        best_score = 0.0

        for entity_id, ref in gallery.items():
            # Skip entities that have aged out of the retention window.
            if not self._has_recent_sighting(entity_type, entity_id):
                continue
            score = cosine_similarity(emb, ref)
            if score > best_score:
                best_score = score
                best_id = entity_id

        if best_id is not None and best_score >= match_threshold:
            return best_id, best_score
        return None, best_score

    def _has_recent_sighting(self, entity_type: str, entity_id: str) -> bool:
        key = self._entity_key(entity_type, entity_id)
        return len(self._sightings.get(key, [])) > 0

    def _update_gallery(self, entity_type: str, entity_id: str, emb: np.ndarray) -> None:
        """Blend a new embedding into an entity's gallery via running mean."""
        ref = self._galleries[entity_type].get(entity_id)
        n = self._gallery_counts[entity_type].get(entity_id, 0)
        if ref is None or n == 0:
            self._galleries[entity_type][entity_id] = l2_normalize(emb)
            self._gallery_counts[entity_type][entity_id] = 1
            return
        # Incremental mean, then re-normalise.
        blended = (ref * n + l2_normalize(emb)) / (n + 1)
        self._galleries[entity_type][entity_id] = l2_normalize(blended)
        self._gallery_counts[entity_type][entity_id] = n + 1

    def _parse_ts(self, ts_str: str) -> Optional[datetime]:
        try:
            return datetime.fromisoformat(ts_str)
        except (ValueError, TypeError):
            return None

    def _check_impossible_travel(
        self, key: str, entity_type: str, entity_id: str, camera_id: str, timestamp: str
    ) -> Optional[CrossCameraAlert]:
        """Check if entity was at a different camera impossibly recently."""
        entries = self._sightings.get(key, [])
        if len(entries) < 2:
            return None

        # Compare with the previous sighting
        current = entries[-1]
        previous = entries[-2]

        if previous["camera_id"] == camera_id:
            return None

        t_prev = self._parse_ts(previous["timestamp"])
        t_now = self._parse_ts(timestamp)
        if t_prev is None or t_now is None:
            return None

        seconds_between = abs((t_now - t_prev).total_seconds())

        if seconds_between < self.min_travel_seconds:
            return CrossCameraAlert(
                alert_type="impossible_travel",
                entity_type=entity_type,
                entity_id=entity_id,
                cameras=[previous["camera_id"], camera_id],
                timestamps=[previous["timestamp"], timestamp],
                message=(
                    f"Impossible travel: {entity_type} '{entity_id}' seen at "
                    f"{previous['camera_id']} and {camera_id} within {int(seconds_between)}s "
                    f"(minimum expected: {int(self.min_travel_seconds)}s)"
                ),
                severity=4,
            )
        return None

    def _check_frequent_reappearance(
        self, key: str, entity_type: str, entity_id: str
    ) -> Optional[CrossCameraAlert]:
        """Check if entity was seen at many different cameras in a short window."""
        entries = self._sightings.get(key, [])
        window_cutoff = datetime.now() - timedelta(minutes=self.reappearance_window_minutes)

        recent = [
            e for e in entries
            if self._parse_ts(e["timestamp"]) and self._parse_ts(e["timestamp"]) >= window_cutoff
        ]

        unique_cameras = list({e["camera_id"] for e in recent})

        if len(unique_cameras) >= self.reappearance_camera_threshold:
            return CrossCameraAlert(
                alert_type="frequent_reappearance",
                entity_type=entity_type,
                entity_id=entity_id,
                cameras=unique_cameras,
                timestamps=[e["timestamp"] for e in recent],
                message=(
                    f"Entity of interest: {entity_type} '{entity_id}' seen at "
                    f"{len(unique_cameras)} cameras within {int(self.reappearance_window_minutes)} min: "
                    f"{', '.join(unique_cameras)}"
                ),
                severity=3,
            )
        return None

    def entity_summary(self, entity_type: str, hours: int = 24) -> List[Dict[str, Any]]:
        """Per-entity sighting counts within the window — the honest answer to
        "how many of those detections are the SAME vehicle?". Entities are
        appearance-ReID clusters from our own cameras (continuity, no identity
        claim). Sorted most-seen first.

        Returns [{entity_id, count, first_seen, last_seen, cameras, hours: [24]}]
        (hours = sighting count per local hour-of-day bucket, UTC)."""
        cutoff = datetime.now() - timedelta(hours=hours)
        prefix = f"{entity_type}:"
        out = []
        for key, entries in self._sightings.items():
            if not key.startswith(prefix):
                continue
            recent = []
            for e in entries:
                ts = self._parse_ts(e["timestamp"])
                if ts is not None and ts >= cutoff:
                    recent.append((ts, e))
            if not recent:
                continue
            recent.sort(key=lambda r: r[0])
            hour_buckets = [0] * 24
            for ts, _e in recent:
                hour_buckets[ts.hour] += 1
            out.append({
                "entity_id": key[len(prefix):],
                "count": len(recent),
                "first_seen": recent[0][0].isoformat(),
                "last_seen": recent[-1][0].isoformat(),
                "cameras": sorted({e["camera_id"] for _ts, e in recent}),
                "hours": hour_buckets,
                "days": len({ts.date() for ts, _e in recent}),
                "active_hours": sum(1 for n in hour_buckets if n > 0),
            })
        out.sort(key=lambda r: r["count"], reverse=True)
        return out

    def get_entity_trail(self, entity_type: str, entity_id: str, hours: int = 24) -> List[Dict[str, Any]]:
        """
        Get chronological trail of where an entity has been seen.

        Returns list of {camera_id, timestamp, metadata} sorted by time.
        """
        key = self._entity_key(entity_type, entity_id)
        entries = self._sightings.get(key, [])

        cutoff = datetime.now() - timedelta(hours=hours)
        recent = [
            e for e in entries
            if self._parse_ts(e["timestamp"]) and self._parse_ts(e["timestamp"]) >= cutoff
        ]

        recent.sort(key=lambda e: e["timestamp"])
        return recent

    def get_camera_activity(self, camera_id: str, hours: int = 1) -> Dict[str, Any]:
        """Get activity summary for a camera."""
        cutoff = datetime.now() - timedelta(hours=hours)
        total = 0
        entity_types: Dict[str, int] = defaultdict(int)

        for key, entries in self._sightings.items():
            for e in entries:
                if e["camera_id"] == camera_id:
                    ts = self._parse_ts(e["timestamp"])
                    if ts and ts >= cutoff:
                        total += 1
                        etype = key.split(":")[0]
                        entity_types[etype] += 1

        return {
            "camera_id": camera_id,
            "hours": hours,
            "total_sightings": total,
            "by_type": dict(entity_types),
        }


# Global singleton
_tracker_instance: Optional[CrossCameraTracker] = None


def get_cross_camera_tracker() -> CrossCameraTracker:
    """Get or create global cross-camera tracker."""
    global _tracker_instance
    if _tracker_instance is None:
        _tracker_instance = CrossCameraTracker()
    return _tracker_instance
